<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
	  <UserSecretsId>de10b01f-7a94-485c-bf2f-9d1ee04e2526</UserSecretsId>

  </PropertyGroup>

  <ItemGroup>
    <Compile Include="D:\Git\cella\Cella.Models\DeliveryEvidenceDtos.cs" Link="DeliveryEvidenceDtos.cs" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.5" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.3" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="9.0.5" />
	  <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="QuestPDF" Version="2025.5.0" />
	  <PackageReference Include="Scalar.AspNetCore" Version="2.0.21" />
	  <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
	  <PackageReference Include="Swashbuckle" Version="5.6.0" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
	  <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="7.3.1" />
	  <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.2" />
	  <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.2" />
	  <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.2" />
	  <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.2" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.2" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2" />
	  <PackageReference Include="Serilog" Version="4.2.0" />
	  <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
	  <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
	  <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />

	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cella.Domain\Cella.Domain.csproj" />
    <ProjectReference Include="..\Cella.Infrastructure\Cella.Infrastructure.csproj" />
    <ProjectReference Include="..\Cella.Models\Cella.Models.csproj" />
  </ItemGroup>

</Project>
